# Generated by Django 4.1.7 on 2023-02-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('data_aniversario', models.DateField()),
                ('telefone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
            ],
        ),
    ]
